#iNtErACtioN: 1= Firm J suppLiEs to Firm i, 0= Firm J DoEs Not suppLy to Firm i
FirmA	FirmA	0
FirmA	FirmB	1
FirmA	FirmC	1
FirmA	FirmD	0
FirmA	FirmE	0
FirmA	FirmF	0
FirmA	FirmG	0
FirmA	FirmH	0
FirmA	FirmI	0
FirmA	FirmJ	0
FirmA	FirmK	0
FirmA	FirmL	0
FirmA	FirmM	0
FirmA	FirmN	0
FirmB	FirmA	0
FirmB	FirmB	0
FirmB	FirmC	1
FirmB	FirmD	1
FirmB	FirmE	0
FirmB	FirmF	0
FirmB	FirmG	0
FirmB	FirmH	0
FirmB	FirmI	0
FirmB	FirmJ	0
FirmB	FirmK	0
FirmB	FirmL	0
FirmB	FirmM	0
FirmB	FirmN	0
FirmC	FirmA	0
FirmC	FirmB	0
FirmC	FirmC	0
FirmC	FirmD	1
FirmC	FirmE	1
FirmC	FirmF	0
FirmC	FirmG	0
FirmC	FirmH	0
FirmC	FirmI	0
FirmC	FirmJ	0
FirmC	FirmK	0
FirmC	FirmL	0
FirmC	FirmM	0
FirmC	FirmN	0
FirmD	FirmA	0
FirmD	FirmB	0
FirmD	FirmC	0
FirmD	FirmD	0
FirmD	FirmE	1
FirmD	FirmF	1
FirmD	FirmG	0
FirmD	FirmH	0
FirmD	FirmI	0
FirmD	FirmJ	0
FirmD	FirmK	0
FirmD	FirmL	0
FirmD	FirmM	0
FirmD	FirmN	0
FirmE	FirmA	0
FirmE	FirmB	0
FirmE	FirmC	0
FirmE	FirmD	0
FirmE	FirmE	0
FirmE	FirmF	1
FirmE	FirmG	1
FirmE	FirmH	0
FirmE	FirmI	0
FirmE	FirmJ	0
FirmE	FirmK	0
FirmE	FirmL	0
FirmE	FirmM	0
FirmE	FirmN	0
FirmF	FirmA	0
FirmF	FirmB	0
FirmF	FirmC	0
FirmF	FirmD	0
FirmF	FirmE	0
FirmF	FirmF	0
FirmF	FirmG	1
FirmF	FirmH	1
FirmF	FirmI	0
FirmF	FirmJ	0
FirmF	FirmK	0
FirmF	FirmL	0
FirmF	FirmM	0
FirmF	FirmN	0
FirmG	FirmA	0
FirmG	FirmB	0
FirmG	FirmC	0
FirmG	FirmD	0
FirmG	FirmE	0
FirmG	FirmF	0
FirmG	FirmG	0
FirmG	FirmH	1
FirmG	FirmI	1
FirmG	FirmJ	0
FirmG	FirmK	0
FirmG	FirmL	0
FirmG	FirmM	0
FirmG	FirmN	0
FirmH	FirmA	0
FirmH	FirmB	0
FirmH	FirmC	0
FirmH	FirmD	0
FirmH	FirmE	0
FirmH	FirmF	0
FirmH	FirmG	0
FirmH	FirmH	0
FirmH	FirmI	1
FirmH	FirmJ	1
FirmH	FirmK	0
FirmH	FirmL	0
FirmH	FirmM	0
FirmH	FirmN	0
FirmI	FirmA	0
FirmI	FirmB	0
FirmI	FirmC	0
FirmI	FirmD	0
FirmI	FirmE	0
FirmI	FirmF	0
FirmI	FirmG	0
FirmI	FirmH	0
FirmI	FirmI	0
FirmI	FirmJ	1
FirmI	FirmK	1
FirmI	FirmL	0
FirmI	FirmM	0
FirmI	FirmN	0
FirmJ	FirmA	0
FirmJ	FirmB	0
FirmJ	FirmC	0
FirmJ	FirmD	0
FirmJ	FirmE	0
FirmJ	FirmF	0
FirmJ	FirmG	0
FirmJ	FirmH	0
FirmJ	FirmI	0
FirmJ	FirmJ	0
FirmJ	FirmK	1
FirmJ	FirmL	1
FirmJ	FirmM	0
FirmJ	FirmN	0
FirmK	FirmA	0
FirmK	FirmB	0
FirmK	FirmC	0
FirmK	FirmD	0
FirmK	FirmE	0
FirmK	FirmF	0
FirmK	FirmG	0
FirmK	FirmH	0
FirmK	FirmI	0
FirmK	FirmJ	0
FirmK	FirmK	0
FirmK	FirmL	1
FirmK	FirmM	1
FirmK	FirmN	0
FirmL	FirmA	0
FirmL	FirmB	0
FirmL	FirmC	0
FirmL	FirmD	0
FirmL	FirmE	0
FirmL	FirmF	0
FirmL	FirmG	0
FirmL	FirmH	0
FirmL	FirmI	0
FirmL	FirmJ	0
FirmL	FirmK	0
FirmL	FirmL	0
FirmL	FirmM	1
FirmL	FirmN	1
FirmM	FirmA	1
FirmM	FirmB	0
FirmM	FirmC	0
FirmM	FirmD	0
FirmM	FirmE	0
FirmM	FirmF	0
FirmM	FirmG	0
FirmM	FirmH	0
FirmM	FirmI	0
FirmM	FirmJ	0
FirmM	FirmK	0
FirmM	FirmL	0
FirmM	FirmM	0
FirmM	FirmN	1
FirmN	FirmA	1
FirmN	FirmB	1
FirmN	FirmC	0
FirmN	FirmD	0
FirmN	FirmE	0
FirmN	FirmF	0
FirmN	FirmG	0
FirmN	FirmH	0
FirmN	FirmI	0
FirmN	FirmJ	0
FirmN	FirmK	0
FirmN	FirmL	0
FirmN	FirmM	0
FirmN	FirmN	0